import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home({list}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Filmes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         
         Filmes em Destaques <br/> 
        
        </h1>
        


        <ul>
          
          {list.map(item=>(
            <li>
              <img src={`https://image.tmdb.org/t/p/original${item.poster_path}`} width="350"  /> <br/>
              <p><b>Filme: {item.title}</b></p>
              <p><b>Nota:</b> {item.vote_average} </p> 
              <small><b>Descrição:</b> {item.overview}</small>      
            </li>
          ))}
        </ul>
        

        

        
      </main>

      <footer className={styles.footer}>
        
         Densevolvido{' '}
          <span className={styles.logo}>
           Por Emerson Max
          </span>
       
      </footer>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch('http://localhost:3000/api/trending')
  const json = await res.json();
  return {
    props: {
      list: json.list
      
    }
  };
}
